# Bike Sharing 

# Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Data Preprocessing

In [2]:
ls

P_Practice Bike Sharing.ipynb  test.csv
data.csv                       train.csv
sampleSubmission.csv


In [3]:
dataset = pd.read_csv('train.csv')
df1 = dataset.copy()
df1.head()

datetime  season  holiday  workingday  weather  temp   atemp  \
0  2011-01-01 00:00:00       1        0           0        1  9.84  14.395   
1  2011-01-01 01:00:00       1        0           0        1  9.02  13.635   
2  2011-01-01 02:00:00       1        0           0        1  9.02  13.635   
3  2011-01-01 03:00:00       1        0           0        1  9.84  14.395   
4  2011-01-01 04:00:00       1        0           0        1  9.84  14.395   

   humidity  windspeed  casual  registered  count  
0        81        0.0       3          13     16  
1        80        0.0       8          32     40  
2        80        0.0       5          27     32  
3        75        0.0       3          10     13  
4        75        0.0       0           1      1

In [4]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10886 entries, 0 to 10885
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   datetime    10886 non-null  object 
 1   season      10886 non-null  int64  
 2   holiday     10886 non-null  int64  
 3   workingday  10886 non-null  int64  
 4   weather     10886 non-null  int64  
 5   temp        10886 non-null  float64
 6   atemp       10886 non-null  float64
 7   humidity    10886 non-null  int64  
 8   windspeed   10886 non-null  float64
 9   casual      10886 non-null  int64  
 10  registered  10886 non-null  int64  
 11  count       10886 non-null  int64  
dtypes: float64(3), int64(8), object(1)
memory usage: 1020.7+ KB


In [5]:
df1.isnull().sum()

datetime      0
season        0
holiday       0
workingday    0
weather       0
temp          0
atemp         0
humidity      0
windspeed     0
casual        0
registered    0
count         0
dtype: int64

### Changing the Categorical Data 

In [6]:
from sklearn.preprocessing import LabelEncoder
encoder1 = LabelEncoder()
df1['datetime'] = encoder1.fit_transform(df1['datetime'])
df1.head()

datetime  season  holiday  workingday  weather  temp   atemp  humidity  \
0         0       1        0           0        1  9.84  14.395        81   
1         1       1        0           0        1  9.02  13.635        80   
2         2       1        0           0        1  9.02  13.635        80   
3         3       1        0           0        1  9.84  14.395        75   
4         4       1        0           0        1  9.84  14.395        75   

   windspeed  casual  registered  count  
0        0.0       3          13     16  
1        0.0       8          32     40  
2        0.0       5          27     32  
3        0.0       3          10     13  
4        0.0       0           1      1

### Droping a column having all Unique Value

In [7]:
df1.shape

(10886, 12)

In [8]:
for column, data in df1.items():
    if (df1[column].nunique() == df1.shape[0]):
        df1 = df1.drop(columns = column, axis = 1)       
df1.head()

season  holiday  workingday  weather  temp   atemp  humidity  windspeed  \
0       1        0           0        1  9.84  14.395        81        0.0   
1       1        0           0        1  9.02  13.635        80        0.0   
2       1        0           0        1  9.02  13.635        80        0.0   
3       1        0           0        1  9.84  14.395        75        0.0   
4       1        0           0        1  9.84  14.395        75        0.0   

   casual  registered  count  
0       3          13     16  
1       8          32     40  
2       5          27     32  
3       3          10     13  
4       0           1      1

### Defining Dependent & Independent Variable

In [9]:
X = df1.iloc[:, :-1].values
y = df1.iloc[:, -1].values

In [10]:
X

array([[  1.    ,   0.    ,   0.    , ...,   0.    ,   3.    ,  13.    ],
       [  1.    ,   0.    ,   0.    , ...,   0.    ,   8.    ,  32.    ],
       [  1.    ,   0.    ,   0.    , ...,   0.    ,   5.    ,  27.    ],
       ...,
       [  4.    ,   0.    ,   1.    , ...,  15.0013,   4.    , 164.    ],
       [  4.    ,   0.    ,   1.    , ...,   6.0032,  12.    , 117.    ],
       [  4.    ,   0.    ,   1.    , ...,   8.9981,   4.    ,  84.    ]])

In [11]:
y.shape

(10886,)

# Splitting The DataSet into Training & Test Set

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [13]:
type(X_train), type(y_train)

(numpy.ndarray, numpy.ndarray)

# Model Building

# Random Forest Regression 

In [14]:
from sklearn.ensemble import RandomForestRegressor

### Model Initialization

In [15]:
rfr = RandomForestRegressor(n_estimators = 10, random_state = 0)

### Training the Model

In [16]:
rfr.fit(X_train, y_train)

RandomForestRegressor(n_estimators=10, random_state=0)

### Predicting the Test Set Result

In [17]:
y_rfr_pred = rfr.predict(X_test)

In [18]:
y_test_ver = y_test.reshape(-1, 1)

In [19]:
y_rfr_pred = y_rfr_pred.reshape(-1, 1)

In [20]:
np.concatenate((y_rfr_pred, y_test_ver), axis = 1)

array([[244.7, 244. ],
       [238.5, 239. ],
       [229. , 229. ],
       ...,
       [615.9, 627. ],
       [453.3, 450. ],
       [ 74.5,  75. ]])

### Calculating r2_score

In [21]:
from sklearn.metrics import r2_score
r2_score(y_test, y_rfr_pred)

0.9996039780753267

### Calculating mean_square_error

In [22]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, y_rfr_pred)

13.158163452708912

# Decision Tree Regression

In [23]:
from sklearn.tree import DecisionTreeRegressor

### Initializing the Model

In [24]:
dtr = DecisionTreeRegressor(random_state = 0)

### Training the Model

In [25]:
dtr.fit(X_train, y_train)

DecisionTreeRegressor(random_state=0)

### Predicting the Test Set Result

In [26]:
y_dtr_pred = dtr.predict(X_test)

In [27]:
y_dtr_pred = y_dtr_pred.reshape(-1, 1)

In [28]:
np.concatenate((y_dtr_pred, y_test_ver), axis = 1)

array([[245., 244.],
       [233., 239.],
       [226., 229.],
       ...,
       [607., 627.],
       [456., 450.],
       [ 75.,  75.]])

### Calculating r2_score

In [29]:
r2_score(y_test, y_dtr_pred)

0.9989884461098449

### mean_squared_error

In [30]:
mean_squared_error(y_test, y_dtr_pred)

33.60973370064279

## Support Vector Regression

### Feature Scaling of Training Set

In [31]:
from sklearn.preprocessing import StandardScaler

In [32]:
sc_X = StandardScaler()
sc_y = StandardScaler()

In [33]:
#For featured test set
X_train_svr = sc_X.fit_transform(X_train)

In [34]:
# For outcome test set
y_train_svr = sc_y.fit_transform(y_train.reshape(-1,1))

### Importing SVR & Initializing the model 

In [35]:
from sklearn.svm import SVR

In [36]:
svr = SVR(kernel = 'rbf')

### Training the model

In [37]:
#Transforming 2D array into 1D array as fit method requires 1D array for y_value

In [38]:
svr.fit(X_train_svr, y_train_svr.reshape(-1))

SVR()

### Predicting the Test Set Result

In [39]:
y_pred_svr = svr.predict(sc_X.transform(X_test))
y_pred_svr = sc_y.inverse_transform(y_pred_svr.reshape(-1,1))

In [40]:
y_pred_svr = np.round(y_pred_svr).astype(int)

In [41]:
np.concatenate((y_pred_svr.reshape(-1,1),y_test.reshape(-1,1)), axis = 1)

array([[242, 244],
       [230, 239],
       [233, 229],
       ...,
       [620, 627],
       [468, 450],
       [ 63,  75]])

### Calculating r2_score

In [42]:
r2_score(y_test, y_pred_svr)

0.9964529698814164

### Calculating mean_squared_error

In [43]:
mean_squared_error(y_test, y_pred_svr)

117.85307621671258